### ISSUE TITLE
The only allowed java versions are 8 and 11

### ISSUE THREAD

**Issue by yaquino-kubra** [puppets-epic-show-theatre/puppet-nexus#67]
Recently, Nexus has stated that the newer versions will only run with Java version 17. The module only allows version 8 and 11. 
I believe the module uses the java version to compose the url from where it will download the Nexus installer, that's another thing that changed.
Please if you can address this.
Thank you.

**Comment by PiR-B** [comment]
Hi,
I'll check it today.
Thanks for letting me know.

**Comment by PiR-B** [comment]
Hi @yaquino-kubra ,

Here is the PR https://github.com/puppets-epic-show-theatre/puppet-nexus/pull/68

Do you have a valid licence for the pro version ?
Please keep in mind that postgresql is **NOT** supported on the **OSS version**.

---

**Migration  to a new database -> Follow this link : https://help.sonatype.com/en/migrating-to-a-new-database.html**
I won't bring any support if you break something. In my case it's not very important since I mainly use nexus for proxy features. Besides, you can easily reconstruct your nexus with those ressources : nexus::resource::repository::*

This is just an example :

```
  create_resources(nexus::resource::blobstore::file, $blobstore_file)
  create_resources(nexus::resource::repository::apt::proxy, $apt_proxy)
  create_resources(nexus::resource::repository::docker::proxy, $docker_proxy)
  create_resources(nexus::resource::repository::pypi::proxy, $pypi_proxy)
  create_resources(nexus::resource::repository::rubygems::proxy, $rubygems_proxy)
```

```
blobstore_file:
  default:
    ensure: absent
  apt-debian:
    path: /opt/nexus-storage/blobstore/apt-debian
    ensure: present

apt_proxy:
  apt-debian:
    apt_distribution: bullseye
    proxy_remote_url: https://deb.debian.org/debian/
    cleanup_policy_names:
      - apt

docker_proxy:
  docker-proxy:
    proxy_remote_url: https://registry-1.docker.io/
    docker_http_port: 18080
    docker_force_basic_auth: false
  docker-ghcr:
    proxy_remote_url: https://ghcr.io/
    docker_http_port: 18081
    docker_force_basic_auth: false

pypi_proxy:
  pypi:
    proxy_remote_url: https://pypi.org

rubygems_proxy:
  rubygems:
    proxy_remote_url: https://rubygems.org/
```

Please let me know if you need additional resources

---

Regarding the puppet-nexus
Before  - please adapt your variables

```
  java::adopt { 'jdk11' :
    ensure       => 'present',
    version      => '11',
    java         => 'jdk',
    proxy_type   => 'https',
    proxy_server => $download_proxy,
  }
  -> class { 'nexus':
    version                    => $nexus_version,
    java_runtime               => $java_runtime,
    host                       => $host,
    download_site              => $download_site,
    download_proxy             => $download_proxy,
    purge_default_repositories => $purge_default_repositories,
    require                    => [
      File['/opt/nexus-storage/blobstore'],
    ],
  }
```

After :

```
  java::adoptium { 'jdk17' :
    ensure        => 'present',
    version_major => '17',
    version_minor => '0',
    version_patch => '12',
    version_build => '7',
    proxy_type    => 'https',
    proxy_server  => $download_proxy,
  }
  -> class { 'nexus':
    version                    => $nexus_version,
    # java_runtime               => $java_runtime, # <- Get ride of this parameter
    host                       => $host,
    download_site              => $download_site,
    download_proxy             => $download_proxy,
    purge_default_repositories => $purge_default_repositories,
    manage_datastore           => $manage_datastore, # Has to be true
    # postgresql_username      => $postgresql_username, # <- Only if you have a pro licence - which i don't have - untested
    # postgresql_password      => $postgresql_password, # <- Only if you have a pro licence - which i don't have - untested
    # postgresql_jdbcurl       => $postgresql_jdbcurl, # <- Only if you have a pro licence - which i don't have - untested
    require                    => [
      File['/opt/nexus-storage/blobstore'],
    ],
  }
```

---

It might be possible that the new version put this file in your filestore `/opt/sonatype/sonatype-work/nexus3/admin.password`
Just get ride of it or you will get the following error :

```
Error: /Stage[main]/Nexus::Config::Admin/Nexus_user[admin]: Could not evaluate: authentication error
```

---

cc @TuningYourCode
